# Copyright (c) 2026 Mike Grier

[workspace]
members = [
	"crates/windows-overlapped-io-sys",
	"crates/windows-threadpool-sys",
]
resolver = "2"

[workspace.package]
authors = ["Mike Grier"]
edition = "2024"
rust-version = "1.97"
license = "MIT"
repository = "https://github.com/MikeGrier/windows-threadpool-sys"
homepage = "https://github.com/MikeGrier/windows-threadpool-sys"

[profile.release]
strip = "symbols"
lto = "thin"
codegen-units = 1
