# Copyright (c) 2026 Mike Grier

[workspace]
members = ["crates/your-crate-name"]
resolver = "2"

[workspace.package]
version = "0.1.0" # x-release-please-version
authors = ["Your Name <you@example.com>"]
edition = "2024"
rust-version = "1.97"
license = "MIT"
repository = "https://github.com/OWNER/REPOSITORY"
homepage = "https://github.com/OWNER/REPOSITORY"
documentation = "https://docs.rs/your-crate-name"

[profile.release]
strip = "symbols"
lto = "thin"
codegen-units = 1
